### ISSUE TITLE
Fix Acces-Control-Allow-Origin

### ISSUE THREAD

**Issue by wilfredonoyola** [fhereduardo90/clifre#3]
This is error:
XMLHttpRequest cannot load https://clifre.herokuapp.com/companies. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://0.0.0.0:9000' is therefore not allowed access.
5livereload.js?snipver=1:191 WebSocket connection to 'ws://0.0.0.0:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED.

Please help me with this.

Thanks

**Comment by fhereduardo90** [comment]
working on it :+1: @wilfredonoyola

**Comment by wilfredonoyola** [comment]
Thanks for you support

**Comment by fhereduardo90** [comment]
@wilfredonoyola  the problem with cors has already fixed.
