### ISSUE TITLE
Error Messages (Email was taken)

### ISSUE THREAD

**Issue by wilfredonoyola** [fhereduardo90/clifre#5]
show message when a new company is registered and is a duplicate mail.

Thanks

**Comment by fhereduardo90** [comment]
ok @wilfredonoyola I'll work in that

**Comment by fhereduardo90** [comment]
@wilfredonoyola currently I'm showing an error message if you try to create a new company with an email that is already registered. this is the error message: 

```
{
  "message": "Company could not be created.",
  "status": 422,
  "errors": [
    "email must be unique"
  ]
}
```
